# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/mac/Desktop/Helper_GUI/helper/GUI/source_ui/device_tab.ui'
#
# Created by: PyQt5 UI code generator 5.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(525, 640)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.control_panel = QtWidgets.QFrame(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.control_panel.sizePolicy().hasHeightForWidth())
        self.control_panel.setSizePolicy(sizePolicy)
        self.control_panel.setMinimumSize(QtCore.QSize(90, 0))
        self.control_panel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.control_panel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.control_panel.setObjectName("control_panel")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.control_panel)
        self.verticalLayout.setContentsMargins(5, -1, 5, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.install_button = QtWidgets.QPushButton(self.control_panel)
        self.install_button.setMinimumSize(QtCore.QSize(125, 0))
        self.install_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.install_button.setObjectName("install_button")
        self.verticalLayout.addWidget(self.install_button)
        self.record_button = QtWidgets.QPushButton(self.control_panel)
        self.record_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.record_button.setObjectName("record_button")
        self.verticalLayout.addWidget(self.record_button)
        self.traces_button = QtWidgets.QPushButton(self.control_panel)
        self.traces_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.traces_button.setObjectName("traces_button")
        self.verticalLayout.addWidget(self.traces_button)
        self.clean_button = QtWidgets.QPushButton(self.control_panel)
        self.clean_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.clean_button.setObjectName("clean_button")
        self.verticalLayout.addWidget(self.clean_button)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.control_panel)
        self.device_display = QtWidgets.QTabWidget(Form)
        self.device_display.setTabPosition(QtWidgets.QTabWidget.East)
        self.device_display.setObjectName("device_display")
        self.device_info_tab = QtWidgets.QWidget()
        self.device_info_tab.setObjectName("device_info_tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.device_info_tab)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.device_info = QtWidgets.QTextBrowser(self.device_info_tab)
        self.device_info.setAcceptDrops(False)
        self.device_info.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.device_info.setObjectName("device_info")
        self.verticalLayout_3.addWidget(self.device_info)
        self.device_display.addTab(self.device_info_tab, "")
        self.device_console_tab = QtWidgets.QWidget()
        self.device_console_tab.setObjectName("device_console_tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.device_console_tab)
        self.verticalLayout_2.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.device_console = QtWidgets.QTextBrowser(self.device_console_tab)
        self.device_console.setAcceptDrops(False)
        self.device_console.setAcceptRichText(False)
        self.device_console.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.device_console.setObjectName("device_console")
        self.verticalLayout_2.addWidget(self.device_console)
        self.device_display.addTab(self.device_console_tab, "")
        self.horizontalLayout.addWidget(self.device_display)
        spacerItem1 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)

        self.retranslateUi(Form)
        self.device_display.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.install_button.setText(_translate("Form", "Install"))
        self.record_button.setText(_translate("Form", "Record Screen"))
        self.traces_button.setText(_translate("Form", "Pull Traces"))
        self.clean_button.setText(_translate("Form", "Clean"))
        self.device_info.setPlaceholderText(_translate("Form", "Loading device information..."))
        self.device_display.setTabText(self.device_display.indexOf(self.device_info_tab), _translate("Form", "Device Information"))
        self.device_display.setTabText(self.device_display.indexOf(self.device_console_tab), _translate("Form", "Console"))

