# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/mac/Desktop/Helper_GUI/helper/GUI/source_ui/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(525, 640)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(525, 450))
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.device_container = QtWidgets.QTabWidget(self.centralwidget)
        self.device_container.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.device_container.setTabsClosable(False)
        self.device_container.setMovable(True)
        self.device_container.setObjectName("device_container")
        self.empty_tab = QtWidgets.QWidget()
        self.empty_tab.setObjectName("empty_tab")
        self.gridLayout = QtWidgets.QGridLayout(self.empty_tab)
        self.gridLayout.setContentsMargins(1, 0, 1, 1)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 3, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 3, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.empty_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 1, 1, 1)
        self.refresh_device_status = QtWidgets.QPushButton(self.empty_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.refresh_device_status.sizePolicy().hasHeightForWidth())
        self.refresh_device_status.setSizePolicy(sizePolicy)
        self.refresh_device_status.setFocusPolicy(QtCore.Qt.NoFocus)
        self.refresh_device_status.setObjectName("refresh_device_status")
        self.gridLayout.addWidget(self.refresh_device_status, 4, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.empty_tab)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/misc_icons/images/close-pressed.png"))
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 8, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 1, 1, 1, 1)
        self.status_console = QtWidgets.QTextBrowser(self.empty_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.status_console.sizePolicy().hasHeightForWidth())
        self.status_console.setSizePolicy(sizePolicy)
        self.status_console.setFocusPolicy(QtCore.Qt.NoFocus)
        self.status_console.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.status_console.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.status_console.setObjectName("status_console")
        self.gridLayout.addWidget(self.status_console, 7, 1, 1, 1)
        self.device_container.addTab(self.empty_tab, "")
        self.verticalLayout_2.addWidget(self.device_container)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 525, 19))
        self.menubar.setNativeMenuBar(False)
        self.menubar.setObjectName("menubar")
        self.about_menu = QtWidgets.QMenu(self.menubar)
        self.about_menu.setObjectName("about_menu")
        self.config_menu = QtWidgets.QMenu(self.menubar)
        self.config_menu.setTearOffEnabled(False)
        self.config_menu.setObjectName("config_menu")
        MainWindow.setMenuBar(self.menubar)
        self.menubar.addAction(self.config_menu.menuAction())
        self.menubar.addAction(self.about_menu.menuAction())

        self.retranslateUi(MainWindow)
        self.device_container.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Android Helper"))
        self.label_2.setText(_translate("MainWindow", "There are currently no devices connected, please check your USB connection."))
        self.refresh_device_status.setText(_translate("MainWindow", "Refresh"))
        self.device_container.setTabText(self.device_container.indexOf(self.empty_tab), _translate("MainWindow", "No devices"))
        self.about_menu.setTitle(_translate("MainWindow", "About"))
        self.config_menu.setTitle(_translate("MainWindow", "Configuration"))

from helper.GUI import icons_rc
